[project]
name = "pymagic"
version = "1.4.0"
description = "Minimalistic server for Clash of Clans"
authors = [
    { name = "user-with-username" },
    { name = "wisedevik" }
]
dependencies = [
    "calltracing==1.0.1",
    "toml==0.10.2",
    "decycle==3.0.0",
    "pyfiglet==1.0.3",
    "sqlalchemy==2.0.43",
    "asyncpg==0.30.0",
    "greenlet==3.5.1"
]
requires-python = ">=3.11"

[tool.hatch.build.targets.wheel]
packages = ["."]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"