name: Format

on:
  push:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install black
      run: pip install black

    - name: Format
      run: black .

    - name: Check
      id: changes
      run: |
        git diff --quiet || echo "changes=true" >> $GITHUB_OUTPUT

    - name: Commit
      if: steps.changes.outputs.changes == 'true'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Format code"
        git push
